name: Publish a Release
on: workflow_dispatch
  # release:
  #   types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm install

        # This is where we would run the commands that generate the individual ZIP files

      - name: Build EXE
        run: npm run build --workspace=patcher

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            'patcher/.build/patcher*.exe'